---
title: "Resume"
toc: true
---

<a href="assets/Jeffrey Ding CV.pdf" class="btn btn-primary btn-lg" download>
  Download PDF Resume
</a>

## Technical Skills

Data Analysis, Data Processing, EDA, Data Mining, Data Visualization, Data Warehousing, Data Modelling, CI/CD,
Machine Learning, AI, Agentic Workflows, Python, Git, R, PostgreSQL, JavaScript, IBM Db2, MongoDB, AWS

## Experience

### Data Manager | Sunnybrook Research Institute
**Feb 2022 -- Feb 2024**

- Abstracted unstructured data from 250+ patients to evaluate wellness and determine treatment efficacy
- Increased trial participation by an estimated 40% by aggregating and screening new patient data
- Accelerated the activation of 10+ new trials through financial and legal submissions
- Liaised with sponsor clients by facilitating on-site/remote visits and reconciling 200+ queries
- Orchestrated the simultaneous conduct of 15+ clinical trials by coordinating cross-functional teams

### Summer Undergraduate Researcher | University Health Network
**May -- Aug 2019**

- Performed regression on open-source data to correlate comorbidities and clinical trial participation
- Investigated provincial healthcare data to optimize the transition of cancer survivors to primary care
- Facilitated 15 research studies by directing patients and maintaining databases with Excel and SPSS

### Machine Learning for Life Science Mentorship | University of Toronto
**Jun 2024 -- Jul 2025**

- Partnered with researchers as a volunteer clinical research coordinator consultant
- Applied learned machine learning and deep learning concepts towards developing independent projects

## Education

### Master of Data Science
**University of British Columbia** | 2025 -- Jun 2026 (Projected)

### Bachelor of Medical Sciences
**University of Western Ontario** | 2017 -- 2021

Honours Specialization in Interdisciplinary Medical Sciences

- GPA 3.7
- The Western Scholarship of Excellence
- Dean's Honor List

## Certifications

- IBM Data Science Professional Specialization | IBM, Coursera 2024
